permissionset 50000 "PermissionSet ABRANE"
{
    Assignable = true;
    Caption = 'ABRANE PermissionSet', MaxLength = 30;
    Permissions =
        

        table "Lien cde transitaire-reception" = X,
        tabledata "Lien cde transitaire-reception" = RMID,

        table "Mes Chantiers" = X,
        tabledata "Mes Chantiers" = RMID,

        table "Entete colisage"= X,
        tabledata "Entete colisage" = RMID,

        table "Contenu colisage"= X,
        tabledata "Ligne fiche BE" = RMID,

        table "Detail colisage"= X,
        tabledata "Detail colisage" = RMID,

        table "Creation/MAJ article"= X,
        tabledata "Creation/MAJ article" = RMID,

        table "Nomenclature saisie article"= X,
        tabledata "Nomenclature saisie article" = RMID,
        table "Statistique container"= X,
        tabledata "Statistique container" = RMID,

        table "Stock dispo pour creer cde"= X,
        tabledata "Stock dispo pour creer cde" = RMID,
    
        table "Conditions acompte"= X,
        tabledata "Conditions acompte" = RMID,
        
        table "Tampon reste a charger par sem"= X,
        tabledata "Tampon reste a charger par sem" = RMID,
         
        table "Ligne feuille rentabilite"= X,
        tabledata "Ligne feuille rentabilite" = RMID,
 
        //table "Phases chantier"= X,
        //tabledata "Phases chantier" = RMID,
        table "Groupe client" = X,
        tabledata "Groupe client" = RMID,
        table "Historique PMP article" = X,
        tabledata "Historique PMP article" = RMID,
        table "Parametrage articles Codifab" = X,
        tabledata "Parametrage articles Codifab" = RMID,
        table "Parametrage taxe eco-mobilier" = X,
        tabledata "Parametrage taxe eco-mobilier" = RMID,
        table "Table multiple" = X,
        tabledata "Table multiple" = RMID,
        table "Taxe eco-mobilier" = X,
        tabledata "Taxe eco-mobilier" = RMID,
        table "Type fournisseur" = X,
        tabledata "Type fournisseur" = RMID,
        table Operations = X,
        tabledata Operations = RMID,
        table "Anomalies affaires ventes" = X,
        tabledata "Anomalies affaires ventes" = RMID,
        table "Valorisation stock à date" = X,
        tabledata "Valorisation stock à date" = RMID,
        table "Ecriture rentabilite" = X,
        tabledata "Ecriture rentabilite" = RMID,
        table Container = X,
        tabledata Container = RMID,
        table Matiere = X,
        tabledata Matiere = RMID,
        table "Reference client" = X,
        tabledata "Reference client" = RMID,
        table "Edit Sales Invoice" = X,
        tabledata "Edit Sales Invoice" = RMID,
        table "Selection fns pour creer cde" = X,
        tabledata "Selection fns pour creer cde" = RMID,
        table Chantier = X,
        tabledata Chantier = RMID,
        table "Etiquettes palettes" = X,
        tabledata "Etiquettes palettes" = RMID,
        table Factor = X,
        tabledata Factor = RMID,
        table Enseigne = X,
        tabledata Enseigne = RMID,
        table "Ligne DEB" = X,
        tabledata "Ligne DEB" = RMID,
        table "OD CA Enseigne" = X,
        tabledata "OD CA Enseigne" = RMID,
        table "Affectations achat vente" = X,
        tabledata "Affectations achat vente" = RMID,
        table "Ligne container" = X,
        tabledata "Ligne container" = RMID,
        codeunit "Posted Sales Invoice - Edit" = X,
        page "Eco Tax Furniture Codes" = X,
        page "Eco Tax FurniturePosting Setup" = X,
        page "Ecriture rentabilite" = X,
        page "Fiche chantier" = X,
        page "Lignes containers" = X,
        page "Liste des chantiers" = X,
        page "Liste des matieres" = X,
        page "Type fournisseur" = X,
        page Factor = X,
        page "Affectations achat vente" = X,
        page "Etiquettes palettes" = X,
        page "Liste groupes" = X,
        page "OD CA Enseigne" = X,
        page "Reference client" = X,
        page "Table multiple" = X,
        page "Edit Sales Inv. Line Unit Cost" = X,
        page "Enseignes" = X;
}
